#!/bin/csh

#$ -M jliu16@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -pe smp 4		 # Specify parallel environment and legal core size
#$ -q gpu		 # Specify queue
#$ -N               # Specify job name

module load python cuda/8.0 tensorflow/0.12-python2        # Required modules

python SensorCount.py -s samples/r_1kr

python Cover_1.py -s ../data/ibmpg1t1/rtest -r sensors/sensor_from_r_1kr_0.9
