#!/bin/csh

#$ -M jliu16@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -pe smp 4		 # Specify parallel environment and legal core size
#$ -q gpu		 # Specify queue
#$ -N MNISTrain	         # Specify job name

module load python cuda/8.0 tensorflow/0.12-python2        # Required modules

python main.py --dataset mnist --input_height=28 --output_height=28 --c_dim=1 --is_train > rec/MNISTrain
